### PR TITLE
Enable scaler attribute on zoomableImage

### PR DESCRIPTION
**Pull request by mshafer1**
* Removed ignored empty strings
* Set default explicitly
* provided method for scale value to be provided (and added example to Limit Switch)

This will cause conflicts with any other branches

### CODE REVIEW

**Comment by JonathanLindsey** [comment]
If we replace the 
```
{% assign img_width = include.width | times: scale %}
{% assign img_height = include.height | times: scale %}
```
lines with
```
{% if include.width > 0 %}
{% assign img_width = include.width | times: scale %}
{% endif %}
{% if include.height > 0 %}
{% assign img_height = include.height | times: scale %}
{% endif %}
```
then we don't have to put in the width and height dimensions for each image.

**Comment by JonathanLindsey** [comment]
Oops that breaks scaling though. If there was a way to get the image width and height from the image, that would work though; I'm just not sure how to do that yet.

**Comment by mshafer1** [comment]
> Oops that breaks scaling though. If there was a way to get the image width and height from the image, that would work though; I'm just not sure how to do that yet.

I think we could integrate the ImageSize Ruby gem (probably building a custom Jekyll plugin like I did in themepuzzler - https://github.com/mshafer1/themepuzzler), but gh-pages does not permit custom plugins for security reasons, so we would have to submit the built pages instead (doable, but I was running into issues with it last night (although, that may be related to testing in a branch then moving to a real branch).

little bit of history - the last version of this website was written in php, and it's downloadableImage and zoomableImage methods looked up the sizes themselves and the zoomable had the optional parameter to scale the size back.

Another option: We could make the height default to "auto" unless specified so that we only have specify the width everywhere.

**Comment by JonathanLindsey** [comment]
The "auto" feature would be nice I think. Just keep in mind the below tip from [here](https://www.w3schools.com/tags/att_img_height.asp). I'm sure you'll know better than I do if that is even relavent. Right now when I refresh the [Limit Switch page](https://www.frclabviewtutorials.com/tutorials/sensors/roborio/limit-switch/) I think I do see the text load and the the pictures load which changes where the text is. It's not really noticeable though. My connection speed is ~28.4 Mbps down.
>Tip: Always specify both the height and width attributes for images. If height and width are set, the space required for the image is reserved when the page is loaded. However, without these attributes, the browser does not know the size of the image, and cannot reserve the appropriate space to it. The effect will be that the page layout will change during loading (while the images load).

**Comment by JonathanLindsey** [comment]
So it might make more since to manually enter the height and have the width be auto than the other way around or it may not make a difference anyway.

**Comment by mshafer1** [comment]
> So it might make more since to manually enter the height and have the width be auto than the other way around or it may not make a difference anyway.

Yep, had the same epiphany. I'll go ahead and merge this one, then add that as a feature to the templates.

**Pull request merged**
